version: '3.4'
services:
  web:
    image: web
    restart: on-failure
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
