
# Dockerfile
FROM --platform=linux/amd64 node:14.16.1 AS dev

WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "yarn.lock", "./"]
RUN yarn
COPY . .

ENV VITE_ASSET_HOST=$VITE_ASSET_HOST

EXPOSE 3000
CMD ["node", "build"]
