theme: jekyll-theme-cayman
title: Canvas Icons
description: An open-source LTI designed for Canvas, allowing insertion of free high-quality icons into pages.
show_downloads: false
# github:
#   zip_url: https://github.com/uoa-compsci399-s2-2021/crowd-captions/releases/latest
